### ISSUE TITLE
Please add semantic version tags

### ISSUE THREAD

**Issue by jeanregisser** [vl4dimir/ObjectiveMixin#7]
I’ve recently added [ObjectiveMixin](https://github.com/CocoaPods/Specs/commit/54602983160b3e16bffaef80310d5f05927aff16) to the [CocoaPods](https://github.com/CocoaPods/CocoaPods) package manager repo.

CocoaPods is a tool for managing dependencies for OSX and iOS Xcode projects and provides a central repository for iOS/OSX libraries. This makes adding libraries to a project and updating them extremely easy and it will help users to resolve dependencies of the libraries they use.

However, ObjectiveMixin doesn't have any version tags. I’ve added the current HEAD as version 0.0.1, but a version tag will make dependency resolution much easier.

[Semantic version](http://semver.org) tags (instead of plain commit hashes/revisions) allow for [resolution of cross-dependencies](https://github.com/CocoaPods/Specs/wiki/Cross-dependencies-resolution-example).

In case you didn’t know this yet; you can tag the current HEAD as, for instance, version 1.0.0, like so:

```
$ git tag -a 1.0.0 -m "Tag release 1.0.0"
$ git push --tags
```

**Comment by vl4dimir** [comment]
Thanks Jean. I added the tag as 1.0.0, as the API seems pretty stable at this point.

**Comment by jeanregisser** [comment]
Great! I've added an updated podspec: https://github.com/CocoaPods/Specs/commit/a839f436bbe725a8ea9900cc20342f37636d6283
